# Generated by hand: add head, importance, location and remove description
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarapp", "0003_alter_event_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="head",
            field=models.CharField(max_length=150, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="importance",
            field=models.CharField(default="normal", max_length=10, choices=[("low", "Low"), ("normal", "Normal"), ("high", "High")]),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=200, null=True, blank=True),
        ),
        # remove old description field
        migrations.RemoveField(
            model_name="event",
            name="description",
        ),
    ]
